export const REQUEST_CREATE_POST = "REQUEST_CREATE_POST";
export const CREATE_POST_ADD = "CREATE_POST_ADD";

export const FETCH_POSTS = "POST/FETCH_POSTS";
export const REQUEST_POSTS = "REQUEST_POSTS";

export const REQUEST_FILTERED_POSTS = "REQUEST_FILTERED_POSTS";
export const FETCH_FILTERED_POSTS = "POST/FETCH_FILTERED_POSTS";

export const REQUEST_DELETE_POST = "REQUEST_DELETE_POST";
export const DELETE_POST = "DELETE_POST";

export const REQUEST_ONE_POST = "REQUEST_ONE_POST";
export const FETCH_ONE_POST = "POST/FETCH_ONE_POST";

export const CHANGE_POST = "CHANGE_POST";
export const REQUEST_CHANGE_POST = "REQUEST_CHANGE_POST";

export const FETCH_LOGIN_USER = "FETCH_LOGIN_USER";
export const REQUEST_LOGIN_USER = "REQUEST_LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const FETCH_AUTH_USER = "FETCH_AUTH_USER";
export const REQUEST_AUTH_USER = "REQUEST_AUTH_USER";

export const REQUEST_COMMENTS = "REQUEST_COMMENTS";
export const FETCH_GET_COMMENTS = "FETCH_GET_COMMENTS";

export const REQUEST_CREATE_COMMENT = "REQUEST_CREATE_COMMENT";
export const CREATE_COMMENT_ADD = "CREATE_COMMENT_ADD";

export const REQUEST_DELETE_COMMENT = "REQUEST_DELETE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
